### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by ratsputin** [guilhemmarchand/iptables-for-splunk#1]
Out of the box, this app does not work correctly with a network-based syslog source.  The default `props.conf` file includes the following which assumes a local log file:

`[source::.../(iptables|ufw).log]`

Either this should be updated in the default package or the documentation should be updated to reflect the configuration change to:

`[linux:netfilter]`

Additionally, on the bottom pane of the Country Analysis dashboard, the following search code is used:

    `iptables_datasource` $hosts$ $traffic_filter$ `filter_badclients` | timechart `inline_customspan` count as Connections by host`

This generates an error, as `inline_customspan` is an unknown macro.  A bit of googling makes it appear that this macro is part of the Nmon for Splunk app.  If that's the case, this should be reflected in the requirements; additionally, as of v1.7.4, the `inline_customspan` macro has been renamed.

Thanks for the work on such a nice dashboard!

**Comment by guilhemmarchand** [comment]
Hello @ratsputin !

Many thanks for opening this issue, I will this shortly.

Guilhem
